version: "3"

services:
  api:
    build: api/
    network_mode: host
    read_only: true
    tmpfs: 
    - /app/submissions
    - /tmp

  react-frontend:
    build: react-frontend/
    network_mode: host
    environment:
    - DISABLE_ESLINT_PLUGIN=true
    read_only: true
    tmpfs:
    - /tmp